spring.application.name=prestamos

#Ejecutar con las variables de entorno
#spring.profiles.active=local 

#Configuracion base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#actualizar bd segun modelos 
spring.jpa.hibernate.ddl-auto=update

#mientras estoy en desarrollo
spring.jpa.show-sql=true

server.address=0.0.0.0
